# @no-redirect
< {%
    request.variables.clearAll()
    request.variables.set("base_name", "t2est1");
%}
POST localhost:8080/users?id={{rid}}
Content-Type: application/json

{
    "name": "{{base_name}}{{$uuid}}",
    "age": 30
}
> {%
    client.global.set("id", response.body.ID);
%}

###
GET localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

