### 생성
< {%
    request.variables.clearAll()
    request.variables.set("base_name", "test");
%}
POST localhost:8080/users
Content-Type: application/json

{
    "name": "{{base_name}}-{{$uuid}}",
    "age": 30
}
> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.ID !== "", "Response body ID is empty");

        client.global.set("id", response.body.ID);
        client.global.set("name", response.body.Name);
        client.global.set("age", response.body.Age);
    });
%}

### 생성 검증
GET localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.Name === client.global.get("name"), "Response body Name is not same :" + response.body.Name + " : " + client.global.get("name"));
        client.assert(response.body.Age == client.global.get("age"), "Response body Age is not same :" + response.body.Age + " : " + client.global.get("age"));
    });
%}


### 재생성 (실패 - 이름 중복)
POST localhost:8080/users
Content-Type: application/json

{
    "name": "{{name}}",
    "age": 30
}
> {%
    client.test("Status code is 500", function () {
        client.assert(response.status === 500, "Response status is not 200");
    });
%}

### 이름 수정
PATCH localhost:8080/users/{{id}}
Content-Type: application/json

{
    "name": "{{base_name}}-{{$uuid}}"
}

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.ID === client.global.get("id"), "Response body ID is not same :" + response.body.ID + " : " + client.global.get("id"));
        client.assert(response.body.Name != client.global.get("name"), "Response body Name is not same :" + response.body.Name + " : " + client.global.get("name"));
        client.assert(response.body.Age == client.global.get("age"), "Response body Age is not same :" + response.body.Age + " : " + client.global.get("age"));

        client.global.set("id", response.body.ID);
        client.global.set("name", response.body.Name);
        client.global.set("age", response.body.Age);
    });
%}

### 이름 수정 검증
GET localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.Name === client.global.get("name"), "Response body Name is not same :" + response.body.Name + " : " + client.global.get("name"));
        client.assert(response.body.Age == client.global.get("age"), "Response body Age is not same :" + response.body.Age + " : " + client.global.get("age"));
    });
%}

### 삭제
DELETE localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 204", function () {
        client.assert(response.status === 204, "Response status is not 204" + response.status);
    });
%}

### 없는 것 또 삭제 (idempotent)
DELETE localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 204", function () {
        client.assert(response.status === 204, "Response status is not 204" + response.status);
    });
%}

### 삭제 검증
GET localhost:8080/users/{{id}}
Content-Type: application/json

> {%
    client.test("Status code is 204", function () {
        client.assert(response.status === 204, "Response status is not 404" + response.status);
    });
%}